import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='w-full h-[60px] bg-black text-white'>This is Header section</div>
        {children}
        <div className='w-full h-[50px] bg-blue-950 text-white'>This is Footer section</div>
        </body>
    </html>
  )
}
